name: Build and Upload APK
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Directory
        id: set_directory
        run: |
          if [[ -d "${{ github.workspace }}/path/to/first/directory" ]]; then
            echo "::set-output name=directory::${{ github.workspace }}/path/to/first/directory"
          elif [[ -d "${{ github.workspace }}/path/to/second/directory" ]]; then
            echo "::set-output name=directory::${{ github.workspace }}/path/to/second/directory"
          else
            echo "Directory not found"
            exit 1
          fi
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: APK
          path: path/to/apk/directory

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: APK

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        with:
          release: ${{ steps.create_release.outputs.upload_url }}
