name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Set Directory
      id: set_directory
      run: |
        if [[ -d "/AnLinux-App/.github/workflows/path/to/first/directory" ]]; then
          echo "::set-output name=directory::/AnLinux-App/.github/workflows/path/to/first/directory"
        elif [[ -d "/AnLinux-App/.github/workflows/path/to/second/directory" ]]; then
          echo "::set-output name=directory::/AnLinux-App/.github/workflows/path/to/second/directory"
        else
          echo "Directory not found"
          exit 1
        fi- name: Release APK
  # You may pin to the exact commit or the version.
  # uses: ShowMeThe/github_action_release@c03188563c3286ccd20cf0d2b1413a134e3cabc9
  uses: ShowMeThe/github_action_release@v0.01
  with:
    # Github secret token to allow automated publishing of APK to release.
    GITHUB_TOKEN: # optional
