name: Build and Package APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Termux
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://f-droid.org/repo/com.termux_117.apk
          sudo apt-get install -y adb
          adb install com.termux_117.apk

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Cache
        uses: actions/cache@v3.3.2
    
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-30'
          ndk-version: '21.4.7075529'

      - name: Install Apktool
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: Install Android Studio
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install android-studio --classic

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Package APK
        run: mv app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug
          path: ${{ github.workspace }}/app-debug.apk

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: static-pages
          folder: dist
