name: Build and Package APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Package APK
      run: mv app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/AnLinux-App/.github/workflows/my-app-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-debug
        path: ${{ github.workspace }}/AnLinux-App/.github/workflows/my-app-debug.apk
