name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Set Directory
      id: set_directory
      run: |
        if [[ -d "/AnLinux-App/.github/workflows/path/to/first/directory" ]]; then
          echo "::set-output name=directory::/AnLinux-App/.github/workflows/path/to/first/directory"
        elif [[ -d "/AnLinux-App/.github/workflows/path/to/second/directory" ]]; then
          echo "::set-output name=directory::/AnLinux-App/.github/workflows/path/to/second/directory"
        else
          echo "Directory not found"
          exit 1
        fi
