name: Build and Package APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Termux
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://termux.com/install.sh
          chmod +x install.sh
          ./install.sh

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-30'
          ndk-version: '21.4.7075529'

      - name: Install Android Studio
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install android-studio --classic

      - name: Install Apktool
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Package APK
        run: mv app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug
          path: ${{ github.workspace }}/app-debug.apk
